version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    groups:
      production-dependencies:
        patterns:
        - "*"
        exclude-patterns:
        - "AutoFixture*"
        - "coverlet*"
        - "FluentAssertions*"
        - "Microsoft.NET.Test*"
        - "NSubstitute*"
        - "Polly.Testing*"
        - "xunit*"
        - "xunit.analyzers"
      test-dependencies:
        patterns:
        - "AutoFixture*"
        - "coverlet*"
        - "FluentAssertions*"
        - "Microsoft.NET.Test*"
        - "NSubstitute*"
        - "Polly.Testing*"
        - "xunit*"
        - "xunit.analyzers"

