<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Debug'">
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Elzik.FmSync.Infrastructure\Elzik.FmSync.Infrastructure.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<None Include="..\TestFiles\**" CopyToOutputDirectory="PreserveNewest" LinkBase="TestFiles\" />
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Remove="TestResults\**" />
	  <EmbeddedResource Remove="TestResults\**" />
	  <None Remove="TestResults\**" />
	</ItemGroup>
	
	<ItemGroup>
		
		<PackageReference Include="coverlet.msbuild">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
 	  <PackageReference Include="Microsoft.NET.Test.Sdk" />
 	  <PackageReference Include="Shouldly" />
 	  <PackageReference Include="SonarAnalyzer.CSharp">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
 	  <PackageReference Include="xunit" />
 	  <PackageReference Include="xunit.analyzers">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
 	  <PackageReference Include="xunit.runner.visualstudio">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
