name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
            matrix:
                os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Build & Test
      run: ./Build/build-and-test.ps1
      shell: pwsh  
    - name: Upoload Coverage Badge
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.CODE_COVERAGE_AUTH_TOKEN }}
        gist_id: 527882e89a938dc78f61a08c300edec4
        gist_description: "code-coverage-${{ github.ref_name }}"
        gist_file_name: fmsync-code-coverage-${{ github.ref_name }}.svg
        file_path: tests/TestResults/badge_shieldsio_linecoverage_green.svg
    - name: Build Windows Installer
      if: (github.ref_name == 'main' ||  github.event_name == 'pull_request') && matrix.os == 'windows-latest'
      run: ./Build/build-windows-installer.ps1
      shell: pwsh  