name: Continuous Integration

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
            matrix:
                os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Build & Test
      run: ./Build/build-and-test.ps1
      shell: pwsh  
    - name: Upload Coverage Badge
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.CODE_COVERAGE_AUTH_TOKEN }}
        gist_id: 527882e89a938dc78f61a08c300edec4
        gist_description: "code-coverage-${{ github.ref_name }}"
        gist_file_name: fmsync-code-coverage-${{ github.ref_name }}.svg
        file_path: tests/TestResults/badge_shieldsio_linecoverage_green.svg
    - name: Build Windows Installer
      if: matrix.os == 'windows-latest'
      run: ./Build/build-windows-installer.ps1
      shell: pwsh
    - name: Tag With SemVer
      if: github.ref_name == 'main'
      run: ./Build/tag-with-semver.ps1
      shell: pwsh
    - name: Debug Output
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      run: Write-Output 'This was a tag push!'
      shell: pwsh
